### ISSUE TITLE
Visual Studio for Mac

### ISSUE THREAD

**Issue by cassionandi** [nunit/nunit-vs-templates#39]
Hi!

Just a little question. Is this template supported for VS 4 Mac?

**Comment by ChrisMaddock** [comment]
No, afraid not. VS for Mac uses an entirely different extension format.

It sounds like an interesting project to try and package the templates here for both IDEs, however! 😄

**Comment by godaged** [comment]
I am a tester and new to coding and was asked to use VS Code with C# and NUnit. I found little help on this. I found out how to add Selenium and NUnit 3 on dotnet core. How can I use NUnit VS Template using CLI in VS Code?

**Comment by rprouse** [comment]
@godaged in the future, I would recommend creating a new issue for questions rather than resurrecting long closed issues. Thanks for searching though 😄 

You can find info on installing and using the NUnit templates for a .NET Core project at https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit#install-the-nunit-project-template
